// define("config", function() {
define(function() {
    //Header image (left side)
    var LEFT_HEADER_IMG = "img/CDSA_Slide_50.png";



    ///window.location.protocol  DO THIS TO ADD SWItch the URLS to HTTP or HTTP
    //  url_prefix = "http" | "https"


    //Header image (right side)
    var RIGHT_HEADER_IMG = "http://cancer.digitalslidearchive.net/imgs/Winship_06-2011/Winship_NCI_shortTag/horizontal/jpg_png/Winship_NCI_shortTag_hz_280.png";
    var RIGHT_HEADER_IMG = "";
    
    // //Specify the BASE API URL
    var BASE_URL = "http://adrc.digitalslidearchive.emory.edu:8080/api/v1";
    // var BASE_URL = "http://computablebrain.emory.edu:8080/api/v1";

    // //What is the collection name we are pulling data from?
    // var COLLECTION_NAME = "Virtual_Folders";
    var COLLECTION_NAME = 'TCGA'
    // var COLLECTION_NAME = 'ADRC_Images';

    // //Do you want to include 3rd dropdown menu for the folders?
    // //ONLY APPLIES FOR THE STANDARD UI
    // var THIRD_MENU = false;

    //which endpoints do we wanna use? TCGA or Girder default endpoints
    var UI = "standard";
    var SLIDE_SELECTOR = "table";
    var SLIDE_SELECTOR = "thumbnails"
    var VIRTUAL = false;

    ENDPOINTS = {
        standard: {
            item: BASE_URL + "/item/{ID}"
        },
        tcga: {
            item: BASE_URL + "/tcga/image/{ID}"
        }
    }

    /* Set which modules we want to load on start up */
    
    /* aperio:  Enables loading XML files generated by Aperio Scanscope
       filters: Adds a window to allow brightness/contrast/hue to be modified */

    MODULE_CONFIG = {
        "aperio": false, 
        "filters": true,
        "pathology": true,
        "annotations": true,
        "tagger" : false,
        "zoomButtons": false,
        "metadata": false
    };

    // tags for tagger. Tags should be found in the tags dictionary in slide metadata
    TAGS = {
        "BrainID": [],
        "Stain": [],
        "StainDate": [],
        "Section": [],
        "Hemi": [],
        "Column": []
    };

    TAGS =
    {}
    // collection name containing the schema folder
    // set to false if schema is not needed
    var SCHEMA_COLLECTION_NAME = "FoxSlideData_RAW";

    return {
        BASE_URL: BASE_URL,
        COLLECTION_NAME: COLLECTION_NAME,
        ENDPOINTS: ENDPOINTS[UI],
        UI: UI,
        SLIDE_SELECTOR: SLIDE_SELECTOR,
        LEFT_HEADER_IMG: LEFT_HEADER_IMG,
        RIGHT_HEADER_IMG: RIGHT_HEADER_IMG,
        SCHEMA_COLLECTION_NAME: SCHEMA_COLLECTION_NAME,
        MODULE_CONFIG: MODULE_CONFIG,
        TAGS: TAGS,
        VIRTUAL: VIRTUAL
    }
});
